service: awsugnsk-demo

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    TODO_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "*"

functions:
  postTodo:
    handler: handler.postTodo
    events:
      - http: 
          path: postTodo
          method: post
  getTodos:
    handler: handler.getTodos
    events:
      - http: 
          path: getTodos
          method: get
  deleteTodo:
    handler: handler.deleteTodo
    events:
      - http: 
          path: deleteTodo/{id}
          method: delete
  updateTodo:
    handler: handler.updateTodo
    events:
      - http: 
          path: updateTodo
          method: put

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.TODO_TABLE}